#!/usr/bin/env bash
# Fix Apache inside container

apt-get update -y
apt-get install -y apache2

service apache2 start

# Confirm Apache is running
if pgrep apache2 > /dev/null; then
    echo "apache2 is running"
fi

# Create the required page
echo "Hello Holberton" | tee /var/www/html/index.html

