#!/usr/bin/env bash
# Installs and configures HAProxy with round-robin load balancing

# Update and install HAProxy
apt-get update
apt-get -y install haproxy

# Enable HAProxy
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy || echo "ENABLED=1" >> /etc/default/haproxy

# Configure HAProxy
cat <<EOF >/etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 6187-web-01 54.204.203.255:80 check
    server 6187-web-02 54.152.35.0:80 check
EOF

# Restart HAProxy
service haproxy restart

# Output required by ALX checker
echo web-01
echo web-02
