#!/usr/bin/env bash
# Install and start nginx to listen on port 80

sudo apt-get update -y >/dev/null 2>&1
sudo apt-get install -y nginx >/dev/null 2>&1
sudo systemctl start nginx
sudo systemctl enable nginx

exit 2
