#!/usr/bin/env bash
# Install nginx, start it, and ensure it listens on port 80

sudo apt-get update -y >/dev/null 2>&1
sudo apt-get install -y nginx >/dev/null 2>&1
sudo systemctl start nginx
sudo systemctl enable nginx
